
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: clinic_crm_postgres
    environment:
      POSTGRES_DB: clinic_crm
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic_user -d clinic_crm"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  # FastAPI Backend
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: clinic_crm_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://clinic_user:clinic_password@postgres:5432/clinic_crm
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # Descope configuration (set these in your local .env or here)
      - DESCOPE_PROJECT_ID=${DESCOPE_PROJECT_ID}
      - DESCOPE_MANAGEMENT_KEY=${DESCOPE_MANAGEMENT_KEY}
      - DESCOPE_BASE_URL=${DESCOPE_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
  
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  
volumes:
  postgres_data:
